version: "3"
services: 
  db:
    image: postgres:alpine
    container_name: fastapi-todolist-db
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_DB:       ${POSTGRES_DB}
      POSTGRES_USER:     ${POSTGRES_USR}
      POSTGRES_PASSWORD: ${POSTGRES_PWD}
    # env_file: 
    #   - .env
    volumes:
      - ".data/postgres:/var/lib/postgresql/data"

  api:
    build: .
    container_name: fastapi-todolist-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: > 
      sh -c "alembic upgrade head 
      && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  broker-1:
    image: rabbitmq:alpine
    container_name: fastapi-todolist-broker-1
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  celeryworker-1:
    build: .
    container_name: fastapi-todolist-celeryworker-1
    env_file:
      - .env
    depends_on:
      - broker-1
    # volumes:
    #   - "./:/app"
    command: "celery -A app.celery_worker worker -l info"