version: "3"
services: 
  db:
    image: postgres:alpine
    container_name: fastapi-todolist-db
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_DB:       ${POSTGRES_DB}
      POSTGRES_USER:     ${POSTGRES_USR}
      POSTGRES_PASSWORD: ${POSTGRES_PWD}
    env_file: 
      - .env
    volumes:
      - ".data/postgres:/var/lib/postgresql/data"
