version: "3"
services: 
  db:
    image: postgres:latest
    container_name: fastapi-todolist-db
    ports: 
      - "5432:5432"
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todolist
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
