version: "3"
services: 
  db:
    image: postgres:alpine
    container_name: fastapi-todolist-db
    ports: 
      - "5432:5432"
    env_file: 
      - .env
    volumes:
      - ".data/postgres:/var/lib/postgresql/data"
