# This workflow will install Python dependencies and run tests.

name: FastApi-TodoList
defaults:
  run:
    shell: bash

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make install-dev
        
    - name: Run tests
      run: |
        env TEST_DATABASE_URI="sqlite+aiosqlite:///test.db"
        make test
        
